services:
  mongo:
    image: mongo
    container_name: tweeter-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
    container_name: tweeter-backend
    environment:
      - MONGO_URL=mongodb://mongo:27018/tweeterdb
    depends_on:
      - mongo
    networks:
      - tweeter-net

  frontend:
    build:
      context: ./frontend
    container_name: tweeter-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - tweeter-net

